name: Semgrep Scan

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: '58 17 * * *'

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep scan
        run: |
          semgrep ci --json > semgrep_results.json || true

      - name: Extract Semgrep results
        id: semgrep_metrics
        run: |
          TOTAL_FINDINGS=$(jq '.results | length' semgrep_results.json || echo "0")
          BLOCKING_FINDINGS=$(jq '[.results[] | select(.extra.severity == "ERROR")] | length' semgrep_results.json || echo "0")
          WARNINGS=$(jq '[.results[] | select(.extra.severity == "WARNING")] | length' semgrep_results.json || echo "0")
          INFO=$(jq '[.results[] | select(.extra.severity == "INFO")] | length' semgrep_results.json || echo "0")

          echo "TOTAL_FINDINGS=$TOTAL_FINDINGS" >> $GITHUB_ENV
          echo "BLOCKING_FINDINGS=$BLOCKING_FINDINGS" >> $GITHUB_ENV
          echo "WARNINGS=$WARNINGS" >> $GITHUB_ENV
          echo "INFO=$INFO" >> $GITHUB_ENV

      - name: Display Semgrep Results in Annotations
        run: |
          echo "::notice title=Semgrep Security Report::| Severity | Count |
          |----------|-------|
          | 🔥 Blocking Findings | ${{ env.BLOCKING_FINDINGS }} |
          | ⚠️ Warnings | ${{ env.WARNINGS }} |
          | ℹ️ Informational | ${{ env.INFO }} |
          | 📊 Total Findings | ${{ env.TOTAL_FINDINGS }} |"

      - name: Add Detailed Annotations for Findings
        if: env.TOTAL_FINDINGS != '0'
        run: |
          jq -r '.results[] | "::warning file=\(.path),title=Semgrep Issue::\(.extra.message) [Rule: \(.check_id)]"' semgrep_results.json
